plugins {
	id 'fabric-loom' version "${loom_version}"
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	mavenCentral()
	maven {
		name = 'LegacyFabric'
		url = 'https://maven.legacyfabric.net/'
	}
	maven {
		name = 'Ornithe'
		url = 'https://maven.ornithemc.net/releases'
	}
}

loom {
	mods {
		"obs_rec_indicator" {
			sourceSet sourceSets.main
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.legacyfabric:yarn:1.8.9+build.604:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "org.slf4j:slf4j-api:2.0.17"

	compileOnly files(
		"libs/oneconfig-config-1.2.4.jar",
		"libs/oneconfig-config-impl-1.2.4.jar",
		"libs/asm-9.10.1.jar",
		"libs/kotlin-stdlib-2.1.0.jar"
	)
}

processResources {
	inputs.property "version", project.version
	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
	it.options.encoding = "UTF-8"
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}
